# Generated by Django 3.1.1 on 2020-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)]),
        ),
    ]
